name: intro_to_pymc3

channels:
 - defaults

dependencies:
 - python=3.7
 - pip
 - libpython
 - msys2::m2w64-toolchain
 - numpy
 - mkl-service
 - jupyter
 - matplotlib
 - seaborn
 - scipy 
 - patsy 
 - pandas
 - conda-forge::python-graphviz
 - pip:
   - git+https://github.com/pymc-devs/pymc3
   - git+https://github.com/arviz-devs/arviz.git
   - git+https://github.com/Theano/Theano.git
